version: '3'
services:
  # === core services ===
  overview-worker:
    image: overview/overview-worker:${OVERVIEW_VERSION}
    networks: [ 'default', 'worker' ]
    volumes:
      - overview-blob-storage:/var/lib/overview/blob-storage
      - overview-searchindex-data:/var/lib/overview/searchindex
    env_file:
      - overview.defaults.env
      - overview.env

  overview-web:
    image: overview/overview-web:${OVERVIEW_VERSION}
    volumes:
      - overview-blob-storage:/var/lib/overview/blob-storage
    env_file:
      - overview.defaults.env
      - overview.env

  # === internal dependencies ===
  overview-database:
    image: overview/overview-database:${OVERVIEW_VERSION}
    volumes:
      - overview-database-data:/var/lib/postgresql/data

  overview-db-evolution-applier:
    image: overview/overview-db-evolution-applier:${OVERVIEW_VERSION}
    depends_on: [ 'overview-database' ]
    env_file:
      - overview.defaults.env
      - overview.env

  overview-redis:
    image: overview/overview-redis:${OVERVIEW_VERSION}

  # === converters ===
  overview-convert-archive:
    image: "${CONVERT_ARCHIVE_IMAGE}"
    networks: [ 'worker' ]
    depends_on: [ 'overview-worker' ]
    environment:
      POLL_URL: 'http://overview-worker:9032/Archive'

  overview-convert-email:
    image: "${CONVERT_EMAIL_IMAGE}"
    networks: [ 'worker' ]
    depends_on: [ 'overview-worker' ]
    environment:
      POLL_URL: 'http://overview-worker:9032/Email'

  overview-convert-html:
    image: "${CONVERT_HTML_IMAGE}"
    networks: [ 'worker' ]
    depends_on: [ 'overview-worker' ]
    environment:
      POLL_URL: 'http://overview-worker:9032/Html'

  overview-convert-image:
    image: "${CONVERT_IMAGE_IMAGE}"
    networks: [ 'worker' ]
    depends_on: [ 'overview-worker' ]
    environment:
      POLL_URL: 'http://overview-worker:9032/Image'

  overview-convert-office:
    image: "${CONVERT_OFFICE_IMAGE}"
    networks: [ 'worker' ]
    depends_on: [ 'overview-worker' ]
    environment:
      POLL_URL: 'http://overview-worker:9032/Office'

  overview-convert-pdf:
    image: "${CONVERT_PDF_IMAGE}"
    networks: [ 'worker' ]
    depends_on: [ 'overview-worker' ]
    environment:
      POLL_URL: 'http://overview-worker:9032/Pdf'

  overview-convert-pdfocr:
    image: "${CONVERT_PDFOCR_IMAGE}"
    networks: [ 'worker' ]
    depends_on: [ 'overview-worker' ]
    environment:
      POLL_URL: 'http://overview-worker:9032/PdfOcr'

  overview-convert-pst:
    image: "${CONVERT_PST_IMAGE}"
    networks: [ 'worker' ]
    depends_on: [ 'overview-worker' ]
    environment:
      POLL_URL: 'http://overview-worker:9032/Pst'

  overview-convert-text:
    image: "${CONVERT_TEXT_IMAGE}"
    networks: [ 'worker' ]
    depends_on: [ 'overview-worker' ]
    environment:
      POLL_URL: 'http://overview-worker:9032/Text'

  # === plugins ===
  overview-plugin-entity-filter:
    image: overview/overview-entity-filter:1.0.7

  overview-plugin-file-browser:
    image: overview/overview-file-browser:1.0.3

  overview-plugin-metadata:
    image: overview/overview-plugin-metadata:1.0.3

  overview-plugin-multi-search:
    image: overview/overview-multi-search:1.0.4

  overview-plugin-word-cloud:
    image: overview/overview-word-cloud:1.0.1

  # === proxy -- which binds them all
  overview-proxy:
    image: overview/overview-proxy:latest
    volumes:
      - overview-acme:/var/lib/acme
    env_file:
      - overview.defaults.env
      - overview.env
    ports:
      - '127.0.0.1:9000:9000'
      - '127.0.0.1:3011-3021:3000-3010'

volumes:
  overview-acme:
  overview-blob-storage:
  overview-database-data:
  overview-searchindex-data:

networks:
  default:
  worker:
